declare module "remark-rehype";
declare module "rehype-document";
declare module "rehype-stringify";
declare module "rehype-format";
declare module "rehype-add-classes";
declare module "remark-containers";
declare module "rehype-highlight";
declare module "to-vfile";
declare module "vfile-reporter";
